FROM node:20-alpine AS build

WORKDIR /app

COPY . .

RUN npm ci

RUN npm run build

RUN npm install -g serve

ENV BACKEND_URL=http://localhost:8080

RUN chmod +x entrypoint.sh

EXPOSE 3000

CMD ["./entrypoint.sh"]
