# 1. Sélectionne l'image de base du Docker Hub
FROM node:25

# 2. Défini le répertoire de travail dans le conteneur
WORKDIR /app

# 3. Copie de tout le répertoire coutant dans le dossier /app du conteneur
COPY . .

# 4. Installation des dépendences en utilisant npm ci (utilisation du package-lock)
RUN npm ci

# 5. Documente le port d'exposition
EXPOSE 3000

# 6. Défini la commande de démarrage
CMD ["node", "server.js"]
