# ---------- Stage 1 : Build ----------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore
RUN dotnet publish --configuration Release -o /app/publish

# ---------- Stage 2 : Runtime ----------
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Copier les fichiers avec le bon propriétaire
COPY --from=build --chown=app /app/publish .

# Utiliser l'utilisateur intégré .NET
USER app

ENTRYPOINT ["dotnet", "HelloNonRoot.dll"]
