FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet publish --configuration Release -o /app/publish

# Bonne pratique : --mount=type=secret
# Le secret est accessible à /run/secrets/api_key uniquement pendant cette instruction RUN
# Il n'est jamais stocké dans un layer de l'image
RUN --mount=type=secret,id=api_key,required=true \
    API_KEY=$(cat /run/secrets/api_key) && \
    echo "Authentification réussie (clé : ***)" && \
    echo "Simulation d'accès au dépôt privé..."

# Le secret /run/secrets/api_key n'existe plus
RUN ls -ali /run

WORKDIR /app/publish
USER app
ENTRYPOINT ["dotnet", "HelloSecrets.dll"]
