FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

# Copie du csproj et du code
COPY . .

RUN dotnet restore

RUN dotnet publish -c Release -o /app/publish --no-restore

WORKDIR /app/publish

EXPOSE 8080

ENTRYPOINT ["dotnet", "HelloMultiStage.dll"]
