FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet publish --configuration Release -o /app/publish

# Brèche de sécurité : le secret est passé via ARG dans le stage final
# Il sera visible en clair dans : docker history --no-trunc hello-secrets:insecure
ARG API_KEY
RUN echo "Authentification avec la clé : $API_KEY" && \
    echo "Simulation d'accès au dépôt privé..."

WORKDIR /app/publish
USER app
ENTRYPOINT ["dotnet", "HelloSecrets.dll"]
