# ---------- Stage 1 : Build ----------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore
RUN dotnet publish --configuration Release -o /app/publish

# ---------- Stage 2 : Runtime ----------
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

# Créer un utilisateur "appuser" sans shell de login
# (Utiliser la commande useradd)

WORKDIR /app

# Copier les fichiers avec le bon propriétaire (utiliser l'option --chown de COPY)
COPY --from=build /app/publish .

# Basculer vers l'utilisateur non-root avec l'instruction USER

ENTRYPOINT ["dotnet", "HelloNonRoot.dll"]
