# ---------- Stage 1 : Build ----------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore
RUN dotnet publish --configuration Release -o /app/publish

# ---------- Stage 2 : Runtime ----------
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
# Copier les fichiers avec le bon propriétaire (utiliser l'option --chown de COPY)
COPY --from=build /app/publish .

# Utiliser l'utilisateur intégré .NET pour exécuter l'application en non-root
# (les images .NET 8+ fournissent un utilisateur prêt à l'emploi nommé "app")

ENTRYPOINT ["dotnet", "HelloNonRoot.dll"]
